// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfmuztvmdkbmbwzrohji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmbXV6dHZtZGtibWJ3enJvaGppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MzQxNzAsImV4cCI6MjA1ODMxMDE3MH0.qQsBZA_bbxzW8Qb5XkTi2xvr5aYN2u6iJ7LSsUMWvLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);